version: '3.9'

services:
  # frontend:
  #   build: .
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./frontend:/app
  #   command: npm start
  #   depends_on:
  #     - backend

  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000
  #   depends_on:
  #     - database

  # database:
  #   image: postgres:latest
  #   environment:
  #     POSTGRES_DB: inventory_db
  #     POSTGRES_USER: inventory_db
  #     POSTGRES_PASSWORD: inventory_db
